### ISSUE TITLE
Feature Request: Display Telefon Nummer von Restaurant

### ISSUE THREAD

**Issue by ju6ge** [nnev/pizza4c#1]
Es wäre praktisch Zwecks Kommunikation mit dem Restaurant die Telefonnummer nach abschicken der Bestellung an zu zeigen. So kann man ohne die Nummer online zu googlen anrufen und fragen ob alles geklappt hat.

**Comment by k0rmarun** [comment]
Implementiert in v0.1.11 / 4a10896f
